#!/usr/bin/python3

import os;
import hashlib;

from datetime import datetime;
from pathlib  import Path;

from PIL import Image;


def main():
    p = Path("../resources/graphic-tiles").glob("*.png");

    images = [];
    for item in p:
        images.append(str(item));

    images.sort();

    if not images:
        print("No images found!");
        exit(1);

    when = datetime.today().strftime("%Y-%m-%d %H:%M:%S");

    commentBlock = (
      "//\n"
      "// This file was automatically generated by graphic-tiles-maker.py\n"
      "//\n"
      f"// {when}\n"
      "//\n"
    );

    output = (
        "#ifndef GRAPHICTILES_H\n"
        "#define GRAPHICTILES_H\n"
        "\n"
        "enum class GraphicTiles\n"
        "{\n"
        "    NONE = -1\n"
        "  , FIRST = 0\n"
    );
    first = True;
    for item in images:
        spl = item.split(os.sep);
        ln = len(spl);
        fname = spl[ln - 1].replace(".png", "");
        enumName = fname.upper().replace("-", "_");
        if first:
            output += f"  , {enumName} = 0\n";
            first = False;
        else:
            output += f"  , {enumName}\n";

    output += "  , LAST\n";
    output += "};\n";
    output += "\n";
    output += "#endif\n";

    headerFname = Path("../src/extra/graphic-tiles.h");
    headerContents = [];

    if headerFname.is_file():
      headerContents = "\n".join(headerFname.read_text().split('\n')[5:]);

    h1 = hashlib.sha256(headerContents.encode()).digest();
    h2 = hashlib.sha256(output.encode()).digest();

    output = f"{ commentBlock }{ output }";

    emptyCell = Image.new("RGB", (32, 32), color="magenta");

    totalImages = len(images);

    print(f"Found {totalImages} files");

    atlasWidth = 32 * 16;
    atlasHeight = 32 if (totalImages <= 15) else (32 * ((totalImages // 16) + 1));

    print(f"Atlas size: {atlasWidth} x {atlasHeight}");

    graphics = Image.new("RGB", (atlasWidth, atlasHeight), color="magenta");

    print("Pasting graphics...");

    imgPosX = 0;
    imgPosY = 0;
    counter = 1;

    for path in images:
        print(f"Pasting file no. {counter} / {totalImages} ('{path}')...");
        img = Image.open(path);
        graphics.paste(img, (imgPosX, imgPosY), img);
        imgPosX += 32;
        if imgPosX >= atlasWidth:
            imgPosX = 0;
            imgPosY += 32;

        counter += 1;

    print("Pasting blank...");

    graphics.paste(emptyCell, (imgPosX, imgPosY));

    print("Saving tileset...");

    fname = "graphic-tiles.bmp";

    graphics.save(fname);

    print("Moving atlas to resources...");

    dstPath = f"../resources/{fname}";

    if os.path.isfile(dstPath):
        os.unlink(dstPath);

    os.rename(fname, dstPath);

    if h1 != h2:
      print("Writing output to header file...");
      headerFname.write_text(output);
    else:
      print("Header file contents don't need to be changed.");

    print("Done!");

################################################################################

if __name__ == "__main__":
    main()
