name: linux

on:
  workflow_run:
    workflows: ["mingw"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_DIR_LINUX: build-linux

jobs:
  build-linux:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

    - name: CHECKOUT
      uses: actions/checkout@v3

    # --------------------------------------------------------------------------

    - name: INSTALL LIBRARIES
      run: |
           sudo apt update
           sudo apt install -y libsdl2-dev libncurses-dev

    # --------------------------------------------------------------------------

    - name: CONFIGURE CMake (SDL2)
      run: >
           cmake
           -B '${{github.workspace}}/${{ env.BUILD_DIR_LINUX }}'
           -DBUILD_VERSION_TEXT=${{ env.BUILD_VERSION_TEXT }}
           -G Ninja
           -DCMAKE_BUILD_TYPE=Release
           -DBUILD_TESTS=OFF
           -DUSE_SDL=ON

    # --------------------------------------------------------------------------

    - name: BUILD (SDL2)
      run: >
           cmake --build '${{github.workspace}}/${{ env.BUILD_DIR_LINUX }}'
           --config Release

    # --------------------------------------------------------------------------

    - name: CLEANUP BUILD DIR
      run: rm -rf ${{github.workspace}}/${{ env.BUILD_DIR_LINUX }}/*

    # --------------------------------------------------------------------------

    - name: CONFIGURE CMake (ncurses)
      run: >
           cmake
           -B '${{github.workspace}}/${{ env.BUILD_DIR_LINUX }}'
           -DBUILD_VERSION_TEXT=${{ env.BUILD_VERSION_TEXT }}
           -G Ninja
           -DCMAKE_BUILD_TYPE=Release
           -DBUILD_TESTS=OFF

    # --------------------------------------------------------------------------

    - name: BUILD (ncurses)
      run: >
           cmake --build '${{github.workspace}}/${{ env.BUILD_DIR_LINUX }}'
           --config Release
