name: ncurses

on:
  workflow_run:
    workflows: ["MSVC"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_DIR_NCURSES: build-ncurses

jobs:
  build-ncurses:    
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}
    
    steps:
    
    - name: CHECKOUT
      uses: actions/checkout@v3  
           
    # ---------------------------------------------------------------------
    
    - name: SET UP MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: |
                 git 
                 mingw-w64-ucrt-x86_64-gcc 
                 mingw-w64-ucrt-x86_64-cmake 
                 mingw-w64-ucrt-x86_64-ninja 
                 mingw-w64-ucrt-x86_64-ncurses              

    # ---------------------------------------------------------------------

    - name: DEBUG LOGS
      if: true
      run: |
            echo "--- ls /ucrt64/include/ncurses/ ---"
            ls /ucrt64/include/ncurses/
            echo "--- ls /ucrt64/lib/libnc* ---"
            ls /ucrt64/lib/libnc*
            echo "--- cat /ucrt64/include/ncurses/ncurses.h ---"
            cat /ucrt64/include/ncurses/ncurses.h | grep "KEY_"
           
    # ---------------------------------------------------------------------

    #
    # For some fucking reason you still need to manually pass in
    # values into ncurses related variables through command line 
    # even though they are reported to be successfully found by cmake.
    # You can find values to set in msys package registry, 
    # in the list of provided files for a package. 
    # For this workflow it's here:
    #
    # https://packages.msys2.org/packages/mingw-w64-ucrt-x86_64-ncurses
    #
    # Otherwise it won't compile because it can't find <ncurses.h>
    # And by the way find_package() sets DIFFERENT variables: 
    # CURSES_INCLUDE_DIRS and CURSES_LIBRARIES.
    # While here it's:
    # CURSES_INCLUDE_PATH and CURSES_LIBRARY.
    # And it still works somehow.
    # I mean, I don't fucking know anymore - I stop trying to figure out 
    # how this bullshit build system works.
    #
    - name: CONFIGURE CMake
      run: >          
          cmake 
          -B '${{github.workspace}}/${{ env.BUILD_DIR_NCURSES }}'
          -DBUILD_VERSION_TEXT=${{ env.BUILD_VERSION_TEXT }} 
          -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_TESTS=OFF
          -DCURSES_INCLUDE_PATH='/ucrt64/include/ncurses'          
          -DCURSES_LIBRARY='/ucrt64/lib/libncursesw.dll.a'
          
    # ---------------------------------------------------------------------
    
    - name: BUILD      
      run: >
           cmake --build '${{github.workspace}}/${{ env.BUILD_DIR_NCURSES }}' 
           --config Release
           
